### ISSUE TITLE
Homework Mispelled in Readme

### ISSUE THREAD

**Issue by kylerobots** [kylerobots/ssw567-triangle-classification#3]
Homework is mispelled in the readme file

**Comment by YatharthVyas** [comment]
If you are referring to this line:
```
A homework assignment to test a function that classifies triangles based on their side lengths.
```
Then I believe it is spelled correctly unless you meant that it isn't capitalized, In which case please let me know if I should make the change

**Comment by kylerobots** [comment]
> 
> 
> If you are referring to this line:
> 
> ```
> A homework assignment to test a function that classifies triangles based on their side lengths.
> ```
> 
> Then I believe it is spelled correctly unless you meant that it isn't capitalized, In which case please let me know if I should make the change

@YatharthVyas no issue - I was just testing something for class. Thanks for taking a look, though!
